### PR TITLE
Fix `defaultRichTextElements` not resolving

### LINKED ISSUE #1: `defaultRichTextElements` methods only allow `string | string[]` return type
Hi! Playing around with this package as I've used `react-intl` quite a bit and would love to use it in Solid.

I'm trying to configure `defaultRichTextElements` to format translated messages, but I'm getting a type error that the result must return a `string | string[]` which I feel like would kind of defeat the purpose. 
image

Digging into the types it looks like `ResolvedIntlConfig` comes with a generic that defaults to `string` which is used in `FormatXMLElementFn` for `defaultRichTextElements`.
image

I see you export `ResolvedIntlConfig` without the generic type specified.
https://github.com/the-cookbook/solid-intl/blob/a675ae53ab203bb20e88d6c0bbb834a900323f1e/src/types.ts#L3-L4

Should this instead be?:
```ts
type IntlConfig = Partial<Omit<ResolvedIntlConfig<JSXElement>, "locale" | "messages">> &
  Required<Pick<ResolvedIntlConfig<JSXElement>, "locale" | "messages">>;
```
I _think_ this also aligns with the `react-intl` implementation:
https://github.com/formatjs/formatjs/blob/649a386f4437cdb0edb0f7d894d56c7a629e9f37/packages/react-intl/src/types.ts#L19-L23

Thoughts on this? If you agree I can put together a PR. Thanks!

### PR DESCRIPTION
**Pull request by lvl-mattwells**
Fixes #1 

Adjusts types to use `JSXElement` like how `react-intl` uses `ReactNode` ([see here](https://github.com/formatjs/formatjs/blob/649a386f4437cdb0edb0f7d894d56c7a629e9f37/packages/react-intl/src/types.ts)) and adds `defaultRichTextElements` to `process-config` function so that it's included in the Provider.

### CODE REVIEW

File: dev/home/home.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { For } from "solid-js";
+import { For, JSXElement } from "solid-js";
```
Comment (themgoncalves) [inline dev/home/home.tsx]: Could you apply this update?

```tsx
import { For } from "solid-js";
import type { Component, JSXElement } from "solid-js";
```

**Review by themgoncalves — COMMENTED** [review]
@lvl-mattwells Got only a comment for you, after this we can merge your PR and do a new package release :)

**Comment by themgoncalves** [comment]
Oh, we need also to update the README.md to reflect the changes you're introducing, sucha s the following line:

From
`defaultRichTextElements?: Record<string, FormatXMLElementFn<T>>;`

To 
`defaultRichTextElements?: Record<string, FormatXMLElementFn<T>>;`

File: dev/home/home.tsx (hunk 1 above)
Comment (lvl-mattwells) [reply dev/home/home.tsx]: Thanks for the review. Updated!

**Comment by lvl-mattwells** [comment]
> Oh, we need also to update the README.md to reflect the changes you're introducing, sucha s the following line:
> 
> From `defaultRichTextElements?: Record<string, FormatXMLElementFn<T>>;`
> 
> To `defaultRichTextElements?: Record<string, FormatXMLElementFn<T>>;`

I think I understood what you meant and updated accordingly. Let me know if there's anything else!

**Review by themgoncalves — APPROVED** [review]
LGTM

**Comment by themgoncalves** [comment]
@lvl-mattwells just released your fix on `v0.1.2` and added you to the contributors list.

Appreciate the contribution.


https://npmjs.org/package/@cookbook/solid-intl
